components:
  schemas:
    MessagePayload:
      properties:
        obj:
          type: string
        predicate:
          type: string
        receiver:
          type: string
        sender:
          type: string
        subject:
          type: string
      required:
      - obj
      - predicate
      - receiver
      - sender
      - subject
      type: object
    PostedMessage:
      properties:
        id:
          format: int32
          readOnly: true
          type: integer
      type: object
info:
  title: Shared DB Channel API
  version: 1.0.0
openapi: 3.0.2
paths:
  /messages:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessagePayload'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostedMessage'
          description: Returns created message object
